version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tasks-api-go:compose
    container_name: tasks-api
    restart: unless-stopped
    environment:
      DB_PATH: /app/data/tasks.db
      LOG_LEVEL: info
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./data:/app/data
