apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-api-data
  namespace: tasks-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Use the cluster's default StorageClass on Docker Desktop
